version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress          # CHANGE THIS
      MYSQL_DATABASE: wordpress               # CHANGE THIS
      MYSQL_USER: wordpress                   # CHANGE THIS
      MYSQL_PASSWORD: wordpress               # CHANGE THIS


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress            # CHANGE THIS
      WORDPRESS_DB_PASSWORD: wordpress        # CHANGE THIS
      WORDPRESS_DB_NAME: wordpress            # CHANGE THIS
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
 db_data: {}
 wordpress: 
 